
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract helper {
    
    constructor() public {
        tvm.accept();}

    function sha256_private(bytes _private) public view returns (uint256 _hash){
        return tvm.hash(_private);
    }


}